[package]
name = "wasi-grpc-server"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0 WITH LLVM-exception"

[lib]
name = "wasi_grpc_server"
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }

